[42기 이한재] Add : 상세 페이지 조회 기능 구현.
wecode-bootcamp-korea/42-2nd-Hyggesil-backend pull request #10
Opened 2023-03-07 05:54 UTC by jayhanjaelee

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 데이터베이스 작업
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 - 해당 브랜치(PR)에서 구현하고자 하는 하나의 목표 작성
- 상세 페이지 기능 구현

<br />

## :: 구현 사항 설명 - 해당 브랜치(PR)에서 작업한 내용 작성
- 상세 페이지 기능 구현

<br />

## :: 테스트 결과 이미지

<br />

## :: 기타 질문 및 특이 사항

2023-03-07 13:43 UTC, jayhanjaelee commented
수정하고 rebase 하였는데 hotels.test 에서 전체 조회하는 기능에 대한 테스트의 fixture 를 어떤 식으로 만들어야 좋을지 궁금합니다.

2023-03-08 05:19 UTC, Kang-kyunghun requested changes

2023-03-08 05:19 UTC, Kang-kyunghun commented on __test__/hotels.test.js
> +>>>>>>> a43a9a8 ([42기 이한재] Add : 상세 페이지 조회 기능 구현.)
conflict 해결 잘 안 되었어요! 확인해 주세요.

2023-03-08 05:27 UTC, Kang-kyunghun commented
LGTM

2023-03-08 05:27 UTC, merged